name: 'Lyrid Deploy'
branding:
  icon: 'airplay'  
  color: 'green'
description: 'Deploy app on Lyrid'
inputs:
  lyrid-key:  
    description: 'Lyrid Access Key'
    required: true
  lyrid-secret:  
    description: 'Lyrid Access Secret'
    required: true
  lyrid-url:  
    description: 'Lyrid Access Secret'
    required: true
outputs:
  random-number: 
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps: 
    - run: rm -rf ~/.lc || true
      shell: bash
    - run: |
       sudo rm -rf $(which lc) || true
       sudo bash ${{ github.action_path }}/install.sh 
       ls -lart
       curl -kv https://api.staging01.lyrid.io/version
       lc config add --config lyrid_github --key ${{ inputs.lyrid-key }} --secret ${{ inputs.lyrid-secret }} --url ${{ inputs.lyrid-url }}
       lc config list 
       lc user info
       cat ~/.lc/.config.json
       lc code submit
      shell: bash
    - id: random-number-generator
      run: echo "::set-output name=random-id::$(echo $RANDOM)"
      shell: bash
