name: 'Lyrid Deploy'
branding:
  icon: 'airplay'  
  color: 'gray-dark'
description: 'Deploy app on Lyrid'
inputs:
  lyrid-key:  
    description: 'Lyrid Access Key'
    required: true
  lyrid-secret:  
    description: 'Lyrid Access Secret'
    required: true
  lyrid-url:  
    description: 'Lyrid Access Secret'
    required: true
    default: 'https://api.lyrid.io'
runs:
  using: "composite"
  steps: 
    - run: rm -rf ~/.lc || true
      shell: bash
    - run: |
       sudo rm -rf $(which lc) || true
       sudo bash ${{ github.action_path }}/install.sh 
       lc config add --config lyrid_github --key ${{ inputs.lyrid-key }} --secret ${{ inputs.lyrid-secret }} --url ${{ inputs.lyrid-url }}
       lc user info
       lc code submit
      shell: bash
